-- AlterTable
ALTER TABLE "User" ADD COLUMN     "calorieGoal" DOUBLE PRECISION DEFAULT 2000,
ADD COLUMN     "calorieUnit" TEXT DEFAULT 'kcal',
ADD COLUMN     "carbGoal" DOUBLE PRECISION DEFAULT 250,
ADD COLUMN     "fatGoal" DOUBLE PRECISION DEFAULT 65,
ADD COLUMN     "macroUnit" TEXT DEFAULT 'g',
ADD COLUMN     "proteinGoal" DOUBLE PRECISION DEFAULT 150;
