-- AlterTable
ALTER TABLE "Food" ADD COLUMN     "fibre" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "salt" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "saturates" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "sugars" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "MealEntry" ADD COLUMN     "fibre" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "salt" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "saturates" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "sugars" DOUBLE PRECISION NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "fibreGoal" DOUBLE PRECISION NOT NULL DEFAULT 30,
ADD COLUMN     "saltGoal" DOUBLE PRECISION NOT NULL DEFAULT 6,
ADD COLUMN     "saturatesGoal" DOUBLE PRECISION NOT NULL DEFAULT 20,
ADD COLUMN     "sugarsGoal" DOUBLE PRECISION NOT NULL DEFAULT 90;
